### PR TITLE
feat: Internationalization API methods injected with generated locale

### LINKED ISSUE #4: Internationalization API is not injected with locale
**Describe the bug**
The ECMAScript Internationalization API is not affected by the injected fingerprint's `locale`.

**To Reproduce**
See [@mnmkng 's gist](https://gist.github.com/mnmkng/128cd0fe6594081ecad0bb8dbc8f7b40).

**Expected behavior**
The `Intl` methods should return values consistent with the injected `locale`.

**System information:**
 - OS: [Linux Mint 20.2 Cinnamon]
 - Node.js version [16.15.1]

**Additional context**
Originally brought up by @mnmkng in Slack.

### PR DESCRIPTION
**Pull request by barjin**
closes #4 

Causes problems in Firefox tests, needs to be sorted out before merge

### CODE REVIEW

**Comment by mnmkng** [comment]
I'm not familiar with this package, but why not use the locale option of context as[ @petrpatek suggested](https://github.com/apify/fingerprint-suite/issues/4#issuecomment-1164384466)?

**Comment by barjin** [comment]
Current implementation ([`attachFingerprintToPlaywright`](https://github.com/apify/fingerprint-suite/blob/main/packages/fingerprint-injector/src/fingerprint-injector.ts#L38)) accepts already created `BrowserContext` to be injected with the fingerprint (hence the [workaround](https://apify.github.io/fingerprint-suite/docs/guides/fingerprint-injector/#usage-with-the-playwright) with `viewport` and `useragent`). 

Might be worth it to rewrite the method completely, but there is perhaps a good reason to have it like this (using different contexts for fingerprint management etc. ?)

**Comment by mnmkng** [comment]
Please double check this but I think that changing the locale via context actually changes other things as well, like the timezone. Whereas your solution only changes the locale string itself afaik.

**Comment by barjin** [comment]
According to the [docs](https://playwright.dev/docs/api/class-browser#browser-new-context-option-locale), "Locale will affect navigator.language value, Accept-Language request header value **as well as number and date formatting rules**". 

AFAIK timezone cannot be set from language locale setting (has to be fetched from the system information - see e.g. USA).

**Comment by mnmkng** [comment]
I was looking at this, but I guess it's in line with what you're saying. That it only changes formatting rules. It's true that the timezone stays the same.

SNAPSHOT

**Comment by B4nan** [comment]
we should probably change the branching, so development happens in master and stable releases are elsewhere (e.g. `stable`). because right now the `closes #123` in PR descriptions no longer works as the target is not the main branch.

**Comment by barjin** [comment]
Sounds good, IIRC I don't have the rights to rename branches here (or set defaults), so would you look into it please? Renaming will also break Actions, but I can handle that :)

**Comment by mnmkng** [comment]
This repo does not use the standard way of releasing?
- push to master releases beta/next
- manual release triggers a stable release and tags the commit with version?

**Comment by barjin** [comment]
We don't expect many changes once the project is finished (so basically from now on), but we want to automatically generate a new ML model every month and publish it to npm (as a new `patch` version). Pushing to `prepublish` publishes a "next" version.

Aside from renaming the branches, we probably should remove the action causing push to `stable` to publish a stable release? If the versions are not bumped manually though, nothing happens (`npm publish` will fail, because of existing version).

**Pull request merged**
