### PR TITLE
fix: webGl injection.

### PR DESCRIPTION
**Pull request by petrpatek**
The old injection was detected and caused a hard block using fingerprints with Kasada protection. Without fingerprints, it worked fine. Example website: coachaustralia.com

### CODE REVIEW

**Comment by barjin** [comment]
Thanks for the PR! 

I vaguely remember this was done to hide from certain CreepJS detections.

| `master` | `fix/web-gl` (this branch) |
| --- | --- |
|   |  |

I'm not really opinionated here though, CreepJS is just too strict sometimes. Let's merge it and see how it performs over time.

**Comment by petrpatek** [comment]
ouch, that might be a problem. I have tested it with firefox, and since this "fix" the Kasada protection started working.

**Comment by barjin** [comment]
Huh, looking into this a bit deeper now, what was your setup? Mine is most likely tripping Kasada either way (after the initial page, no others are loading).

kasada

**Comment by petrpatek** [comment]
I believe this is not the only difference I made. I have also disabled the headless fixes and Intl API injection. However, the last thing I disabled was the webGL and it started to work.

**Pull request merged**
